# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Bewilder' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Bewilder

pod 'Masonry'
pod 'YYWebImage'
pod 'SDWebImage'
pod 'MBProgressHUD'
pod 'YYModel'
pod 'MJRefresh'
pod 'pop'

end
